# Generated by Django 2.0.4 on 2018-04-19 12:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=13)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.CharField(max_length=6)),
                ('who_invired', models.CharField(max_length=13)),
                ('profession', models.CharField(max_length=30)),
                ('hobby', models.CharField(max_length=30)),
                ('clientid', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('other_images', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MassSendingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('filter', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receiver_count', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(storage=app.models.OverwriteStorage(), upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
