# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_masssendingreport_receiver_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='masssendingreport',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
