# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dailymessaging_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymessaging',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
