# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 08:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180421_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymessaging',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 4, 21)),
        ),
    ]
