# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180421_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymessaging',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
