# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180421_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='good_name',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
