# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coworking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=256)),
                ('user_phone', models.CharField(max_length=13)),
                ('realise_method', models.CharField(max_length=13)),
                ('country_city', models.CharField(max_length=120)),
                ('have_realise_square', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('social_network', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
