# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_coworking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coworking',
            name='user_phone',
        ),
        migrations.AddField(
            model_name='coworking',
            name='sales_count',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
